### ISSUE TITLE
doesnt work with wordops

### ISSUE THREAD

**Issue by blarg3891** [bomsn/rclone-automated-backups-for-wordpress#3]
Looks like a nice option for backups with wordops setup, hoping to get this working.

the config.sh will not find wordpress at /var/www/domain.com/htdocs.  It will find at /var/www/domain.com and add to definitions but will fail on backup saying that "no wordpress installation found"

I modified the cron job with the domain_path="/var/www/kindatakoma.com/htdocs" to get past above issue.  However this receives a permission error. 
[2024-11-08 13:54:36] BACK UP STARTED (full): Performing 01:00 weekly backup for 'domain.com'
[2024-11-08 13:54:36] - Exporting database
[2024-11-08 13:54:36] - WP folder owner found: 'www-data'
[2024-11-08 13:54:36] - WP folder owner home directory found: '/var/www'
mysqldump: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb-dump' instead
mysqldump: Deprecated program name. It will be removed in a future release, use '/usr/bin/mariadb-dump' instead
mysqldump: Can't create/write to file '/var/www/063a4530a71cc1cc79e6aa4fc6aa556e_domain_com_domain_com_2QVJgWDH_08-11-2024_13-54.sql' (Errcode: 13 "Permission denied")

**Comment by bomsn** [comment]
You need add a domain first before setting up backups, and when you add a domain you're requested to enter the full path of the WordPress folder, so it shouldn't make any mistakes or require you to manually overwrite the domain path.

Note that the script evaluates the existence of wp-config.php inside the folder, if you're using Docker, or an unusual setup, it will fail to detect the WordPress directory.

Also, note when running the script, you should run it using a "sudo" user, otherwise, you'll run into unexpected errors.

**Comment by bomsn** [comment]
WordOps structure seems different than the usual WordPress folder structure that's why it's running into issues. Allow me some time until I test this and get back to you

**Comment by blarg3891** [comment]
Yes.  Also, I ran the script manually as root user.  It looks like the cron runs as "root" and does a sudo within the script.  So I may be misunderstanding what needs to be done.  I cant run the script as sudo -u www-data because that user doesnt have perms to the script.  See below.

As another note.  I think wordops is pretty popular these days and does need a nice backup and restore script.  What would be really great would be to just automatically backup everything based on the wordops structure which remains consistent for all domains.

In this way you could just loop through the script and backup all domains.  
For restore, you could just choose what domain to restore etc.

I'm still researching and looking at what other folks have done as well.

Thanks again!

root@wordops-01:/var/www/domain.com# ls -la
total 24
drwxr-xr-x  5 www-data www-data 4096 Nov  8 00:51 .
drwxr-xr-x 12 root     root     4096 Nov  8 02:03 ..
drwxr-xr-x  3 www-data www-data 4096 Nov  8 00:51 conf
drwxr-xr-x  6 www-data www-data 4096 Nov  8 01:53 htdocs
drwxr-xr-x  2 www-data www-data 4096 Nov  8 00:51 logs
-rw-r--r--  1 www-data www-data 3747 Nov  8 00:51 wp-config.php
root@wordops-01:/var/www/domain.com# pwd
/var/www/domain.com
root@wordops-01:/var/www/domain.com# sudo -v

**Comment by blarg3891** [comment]
This guy wrote something that works pretty well.  https://github.com/josephcy95/wpbackup/tree/main.

**Comment by bomsn** [comment]
I made some updates to account for the structure you shared here, but haven't had a chance to directly test WordOps. In all cases, please do test again and let me know if it's working now.
Don't forget to run the script using sudo `sudo bash config.sh`

Please note that this script is much more involved than just setting up a cron job, it allows full management of backups and the ability to view and manage everything, so it's much more complex to extend.

**Comment by bomsn** [comment]
I'll mark this as closed since I haven't heard back from you in a while
